import { Poppins } from "next/font/google";
import { Header } from "@/components/common/header";
import { HomeForm, Matrix } from "@/components/home";

const inter = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const HomePage = () => {
  return (
    <>
      <Header
        title="Home"
        description="Generated by create next app"
        keywords={["matrix", "rotate"]}
        url="https://rotate-matrix.vercel.app"
        urlEs="https://rotate-matrix.vercel.app/es"
      />
      <main className={`center ${inter.className}`}>
        <h1>Prueba técnica: Rotar una matriz</h1>
        <HomeForm />
        <Matrix />
      </main>
    </>
  );
};

export default HomePage;
